export const START_GET_COMMENT_MOVIE_REQUEST = 'SAGAS_WATCH/START_GET_COMMENT_MOVIE_REQUEST';

export const GET_COMMENT_MOVIE_REQUEST = 'COMMENT_MOVIE_ALL/GET_COMMENT_MOVIE_REQUEST';

export const ADD_COMMENT = 'ADD_COMMENT_MOVIE_ID/ADD_COMMENT_REDUX';
